<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Thank you, your order has been placed _cef5f0</name>
   <tag></tag>
   <elementGuidId>021aaa3b-7d0a-4584-b258-353b8eb06add</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.wrapperTwo > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Thank you, your order has been placed successfully You'll be redirected to Home &quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>38b1c5ba-ba33-4212-bf8c-54a83957503f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Thank you, your order has been placed successfully  You'll be redirected to Home page shortly!!</value>
      <webElementGuid>5e384a2d-a799-4a3e-af0c-0f7e1eaffb9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;products-wrapper&quot;]/div[@class=&quot;products&quot;]/div[@class=&quot;wrapperTwo&quot;]/span[1]</value>
      <webElementGuid>5d0bec4c-62df-4a65-b04c-907cffbffae4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/span</value>
      <webElementGuid>b6b85db1-3163-4584-a3b8-f8e67975a642</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KART'])[1]/following::span[1]</value>
      <webElementGuid>4a7af458-5fac-4193-8e86-9b7620de01b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Thank you, your order has been placed successfully']/parent::*</value>
      <webElementGuid>a989728a-2bd1-4505-a982-8a1c1738ddc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/span</value>
      <webElementGuid>d4445f24-4263-48d6-9434-ebb16a697c9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = concat(&quot;Thank you, your order has been placed successfully  You&quot; , &quot;'&quot; , &quot;ll be redirected to Home page shortly!!&quot;) or . = concat(&quot;Thank you, your order has been placed successfully  You&quot; , &quot;'&quot; , &quot;ll be redirected to Home page shortly!!&quot;))]</value>
      <webElementGuid>163cb271-ce96-4dcf-a608-b18cc00aa886</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
