<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Add</name>
   <tag></tag>
   <elementGuidId>fd040d85-50e5-47a3-8be7-b3c570478435</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-info</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>98556bb9-3189-4ead-b97f-d2b6e79cdde8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-info</value>
      <webElementGuid>aeb01058-47ca-4ec7-848c-6bfa49f26080</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add </value>
      <webElementGuid>bc4ff0c4-88ef-4ed1-b4d9-b577514d2ddc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-shop[1]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-9&quot;]/app-card-list[@class=&quot;row&quot;]/app-card[@class=&quot;col-lg-3 col-md-6 mb-3&quot;]/div[@class=&quot;card h-100&quot;]/div[@class=&quot;card-footer&quot;]/button[@class=&quot;btn btn-info&quot;]</value>
      <webElementGuid>3eea6483-2fcb-498e-a579-583699bcfbe4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>de662d1d-6598-40b1-9399-2b43d79b5584</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Add ' or . = 'Add ')]</value>
      <webElementGuid>52bc81f0-cd38-4483-bc69-81d293ae7fb2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
