<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Is this the vehicle you are looking f_9db174</name>
   <tag></tag>
   <elementGuidId>2e82a296-533e-4eb4-b07b-e4cc9e752997</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#yes-vehicle-confirm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='yes-vehicle-confirm']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Yes&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>69683ddc-3ebd-42be-9084-8f067e519bf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-radios__input</value>
      <webElementGuid>12483e16-b5e0-4d95-860d-14641ab9353b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>yes-vehicle-confirm</value>
      <webElementGuid>e51e7627-4d90-41f0-94de-a3674f29c959</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>f1712e17-df04-406b-9a35-dfc1e1875217</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Yes</value>
      <webElementGuid>b3dd9c96-56f2-44a4-b2fc-de71ea87d92c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>wizard_vehicle_enquiry_capture_confirm_vehicle[confirmed]</value>
      <webElementGuid>11cea39d-4ed1-4aee-be21-3a8a5e0b744d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;yes-vehicle-confirm&quot;)</value>
      <webElementGuid>faefd332-b233-449a-8068-88619b6ccfdc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='yes-vehicle-confirm']</value>
      <webElementGuid>bc7d5724-34d5-40c1-975f-b8d8d6bc99ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-content']/div[2]/div/form/div/fieldset/div/div/input</value>
      <webElementGuid>00967b3e-5b86-4922-ba5c-06cd980941a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div/div/input</value>
      <webElementGuid>82d3562e-b401-4a9d-87be-d1d2683c6268</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'yes-vehicle-confirm' and @type = 'radio' and @name = 'wizard_vehicle_enquiry_capture_confirm_vehicle[confirmed]']</value>
      <webElementGuid>d9d5ba86-60e0-4479-b13d-22ec316ed2bc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
