<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dd_2006</name>
   <tag></tag>
   <elementGuidId>6b6019cf-ce62-4274-b6b5-bdbb2cf2a667</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#year_of_manufacture > dd</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='year_of_manufacture']/dd</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;2006&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>dd</value>
      <webElementGuid>69aba77c-4f48-4635-a07a-7b8d717dc896</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>2006</value>
      <webElementGuid>fba3fac1-ea07-470b-b6f3-a4b9d974f413</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;year_of_manufacture&quot;)/dd[1]</value>
      <webElementGuid>e0e593b6-fe98-4a11-8b86-d6e472998ed4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='year_of_manufacture']/dd</value>
      <webElementGuid>309b558d-d3fe-49ff-9cb9-2c087e643da7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Year of manufacture'])[1]/following::dd[1]</value>
      <webElementGuid>ae14a1de-beaa-4054-823d-02317e380b68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='January 2006'])[1]/following::dd[1]</value>
      <webElementGuid>4e4e0864-cd3f-44dd-863b-4690824ea807</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cylinder capacity'])[1]/preceding::dd[1]</value>
      <webElementGuid>adbaa0f1-98a7-4e2e-ac39-39eb3d1b8c8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CO₂ emissions'])[1]/preceding::dd[2]</value>
      <webElementGuid>28227f4b-4289-4ca8-9cbf-eb1adb30fcbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='2006']/parent::*</value>
      <webElementGuid>1688cf96-a348-4eab-9393-7de5d47e92e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/dd</value>
      <webElementGuid>d9ca6a0a-ae9d-482b-82a9-26204d149636</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//dd[(text() = '2006' or . = '2006')]</value>
      <webElementGuid>9800fd6e-cdaa-4d6b-b12a-54a7ee526e12</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
