<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dd_BLACK</name>
   <tag></tag>
   <elementGuidId>728fe326-b04b-4c79-b554-908456d3a816</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#colour > dd</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='colour']/dd</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;BLACK&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>dd</value>
      <webElementGuid>9bee5736-e836-4997-a8cd-6d7d47dee0ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>BLACK</value>
      <webElementGuid>0623c546-e1ed-4709-ba9e-e669e47c804f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;colour&quot;)/dd[1]</value>
      <webElementGuid>de3b6dfa-cd5f-4a1d-9bb2-d4429d9a5de1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='colour']/dd</value>
      <webElementGuid>ca6124da-f780-4a79-8bbe-eabc66e3edba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vehicle colour'])[1]/following::dd[1]</value>
      <webElementGuid>19a97f77-a39e-45c3-b8d8-8224ff2ac245</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Taxed'])[1]/following::dd[1]</value>
      <webElementGuid>a74f9aa1-351c-4e7e-939a-37efc0538e61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vehicle type approval'])[1]/preceding::dd[1]</value>
      <webElementGuid>85f459d0-2b4a-4c02-ae56-2abacddad0de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='M1'])[1]/preceding::dd[1]</value>
      <webElementGuid>7e01c242-e29f-4e5b-9286-ec483e472a0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='BLACK']/parent::*</value>
      <webElementGuid>a019f57d-0725-44db-bb23-bcb66e69024c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/dd</value>
      <webElementGuid>2166b04a-9df5-4eea-b36c-8cd702e4da82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//dd[(text() = 'BLACK' or . = 'BLACK')]</value>
      <webElementGuid>1bec1362-998f-4704-928a-2d759b1bba77</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
