<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dd_MAZDA</name>
   <tag></tag>
   <elementGuidId>824d7f82-71dd-4191-aef1-34b56317590f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>dd</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='make']/dd</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;MAZDA&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>dd</value>
      <webElementGuid>a6ae4299-3c47-47f4-ac57-5a402daf1b84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>MAZDA</value>
      <webElementGuid>acd93cb3-6b89-4c90-bca2-c8cac69f1e2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;make&quot;)/dd[1]</value>
      <webElementGuid>0d02480e-47d9-4117-a0c4-f7b15f089a1c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='make']/dd</value>
      <webElementGuid>5dd519ef-2604-4b62-891f-a25a63b4fbb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vehicle make'])[1]/following::dd[1]</value>
      <webElementGuid>d05c48ec-d840-4668-adf6-819419c09f16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vehicle Details'])[1]/following::dd[1]</value>
      <webElementGuid>a0f2ceb1-c559-45d2-97ad-c6f36956f90f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Date of first registration'])[1]/preceding::dd[1]</value>
      <webElementGuid>b58aa272-2640-4c3f-be98-e96f59dd1136</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='January 2006'])[1]/preceding::dd[1]</value>
      <webElementGuid>874c39f7-2828-4a38-978c-d3971621db62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='MAZDA']/parent::*</value>
      <webElementGuid>6527265c-bb3c-472d-ab69-ab8537e27c74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//dd</value>
      <webElementGuid>9cc6826e-bf80-4795-9603-bbdd2e3bad59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//dd[(text() = 'MAZDA' or . = 'MAZDA')]</value>
      <webElementGuid>ce8ab628-cef9-46dd-abf0-abb9546a6bd0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
