<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dd_PETROL</name>
   <tag></tag>
   <elementGuidId>49227cba-c593-46bb-9026-f443626a7c0c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#fuel_type > dd</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='fuel_type']/dd</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;PETROL&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>dd</value>
      <webElementGuid>58587a48-b574-440f-9a26-7fa3da931594</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PETROL</value>
      <webElementGuid>a8c36ea8-50d8-4973-859c-975c96f25d9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fuel_type&quot;)/dd[1]</value>
      <webElementGuid>682b014d-3fa9-476a-b019-f7d4cdeedd3f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fuel_type']/dd</value>
      <webElementGuid>b249e86b-a5a1-4251-b375-e7bdb4b6b700</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fuel type'])[1]/following::dd[1]</value>
      <webElementGuid>cfd4d22d-666c-4e7c-b72d-3487632c835c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CO₂ emissions'])[1]/following::dd[2]</value>
      <webElementGuid>11ee504c-4013-4011-afd3-57c5acacda93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Euro status'])[1]/preceding::dd[1]</value>
      <webElementGuid>2c5ce14a-4286-4002-b2a3-7a0a09e106be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Not available'])[1]/preceding::dd[1]</value>
      <webElementGuid>5219aec6-6068-450b-89c5-2e09e492d292</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='PETROL']/parent::*</value>
      <webElementGuid>005e6f01-5b47-473a-b8b0-173fec40d218</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/dd</value>
      <webElementGuid>39473fec-8595-4a78-8e1a-b174717a69fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//dd[(text() = 'PETROL' or . = 'PETROL')]</value>
      <webElementGuid>8f789bc0-07c7-4059-a8e3-64e2daa11452</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
