<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_MOT</name>
   <tag></tag>
   <elementGuidId>c6214c77-0f12-4503-b4e4-8e7ddc98d8a1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mot-status-panel']/h2/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;✓ MOT&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>6d469686-cab8-4424-879c-4a776c1afac8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b01f414b-3c88-4cba-a12a-9ce55ac15178</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
✓
MOT
</value>
      <webElementGuid>a7daf0d5-154f-4a20-8f6f-d47f385948f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mot-status-panel&quot;)/h2[@class=&quot;govuk-panel__title govuk-!-font-size-36&quot;]/span[1]</value>
      <webElementGuid>dfedaa5a-c742-41c4-889d-cafd8555e903</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mot-status-panel']/h2/span</value>
      <webElementGuid>647bb1d5-0644-43dd-ab33-2b07e7e5667b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='contact DVLA'])[1]/following::span[1]</value>
      <webElementGuid>01d14304-6056-4238-b7d4-69f690d40c56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Incorrect tax status?'])[1]/following::span[1]</value>
      <webElementGuid>08b52140-4a62-45a4-b5dd-85b26eedb51b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vehicle YY55UVA has a valid MOT certificate'])[1]/preceding::span[1]</value>
      <webElementGuid>5c33cd56-7b2a-4a5c-987b-10007a7ba265</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Expires:'])[1]/preceding::span[2]</value>
      <webElementGuid>00f1f011-f1a2-4ec6-b99a-b32df1abf05a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/h2/span</value>
      <webElementGuid>d1faf00a-ef4c-4d98-b439-e6fb0ed67f5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '
✓
MOT
' or . = '
✓
MOT
')]</value>
      <webElementGuid>39268bea-2a85-4a5f-82d7-690b4bb16d88</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
