<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Overall, how did you feel about the s_523edc</name>
   <tag></tag>
   <elementGuidId>72344e4b-d90e-4000-99c6-2fcaf596f388</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#service-satisfaction-rating-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='service-satisfaction-rating-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Very satisfied&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c33bd868-a8f8-4fa2-9984-455444f4c23e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>c839c839-ac37-4126-92d5-50102d154f9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>service_feedback[service_satisfaction_rating]</value>
      <webElementGuid>49553cf7-3c47-4821-9ee8-f8c493f5419c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>service-satisfaction-rating-0</value>
      <webElementGuid>b7844967-835c-483f-b473-815747861c53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>23dff350-7d8c-4f34-9d4e-085a7a1944ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-radios__input</value>
      <webElementGuid>3758abf4-b658-4dd8-a921-1291d97b75f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;service-satisfaction-rating-0&quot;)</value>
      <webElementGuid>5a24c777-3291-4484-bbf0-e50994179e34</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='service-satisfaction-rating-0']</value>
      <webElementGuid>f3f75985-0368-4b55-a4ee-37aafb65aa01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='content']/div/div[2]/form/div[2]/fieldset/div/div/input</value>
      <webElementGuid>5f28b657-d5f3-4d1c-95ce-2fc095f499c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div/div/input</value>
      <webElementGuid>8ac0a032-0296-4ee0-8260-3bb3854d12de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'service_feedback[service_satisfaction_rating]' and @id = 'service-satisfaction-rating-0']</value>
      <webElementGuid>1b0b5eb9-9de7-4f1f-b174-fecf742f53bb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
