<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_How could we improve this service__e984b6</name>
   <tag></tag>
   <elementGuidId>fe04650e-1315-4d68-b04d-62318e8b551a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#textarea-3c71843f</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='content']/div/div[2]/form/div[3]/div/textarea</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;How could we improve this service?&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>f74af989-78fd-4f2b-92df-203489a444dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>service_feedback[improvement_comments]</value>
      <webElementGuid>fa7db5fb-7327-41b9-a86a-a7f0de1d6e2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-textarea govuk-js-character-count</value>
      <webElementGuid>3bd50e84-9fea-4a60-b454-4079d2aeb65f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>textarea-3c71843f</value>
      <webElementGuid>74bc842f-fad6-4d14-8582-5b99ab9ed9cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>b24840e1-c9da-47bb-9229-6ab5f29398b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4af09b69-884a-4421-980a-74409b7f77b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>hint-24a6ea5b</value>
      <webElementGuid>b72bc920-a9ca-450f-89bd-a407d3dfaefe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;textarea-3c71843f&quot;)</value>
      <webElementGuid>30e3d3bb-679c-41dc-b9dc-dad372f80673</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='textarea-3c71843f']</value>
      <webElementGuid>87944ced-0187-4145-8592-5b142c496258</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='content']/div/div[2]/form/div[3]/div/textarea</value>
      <webElementGuid>9520bb97-51b0-477b-ab7d-4ab805b0f7c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>c20bea76-412f-4516-bf08-7978ca20a9bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'service_feedback[improvement_comments]' and @id = 'textarea-3c71843f']</value>
      <webElementGuid>6ded2e44-329a-4dc6-b150-004e80b0f1cb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
