<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_For example, CU57ABC_wizard_vehicle_e_5f97e0</name>
   <tag></tag>
   <elementGuidId>f8de3107-8395-4293-9027-d4bd4a4058ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#wizard_vehicle_enquiry_capture_vrn_vrn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='wizard_vehicle_enquiry_capture_vrn_vrn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Registration number (number plate)&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a318e85e-d171-4f1f-9931-d322ebf80895</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-input govuk-input--width-10</value>
      <webElementGuid>4c4649cd-49ec-43fd-905d-50f191fb9543</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>50448dc0-f786-42f1-9530-93213fa7617a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>126a19f6-5e70-4635-80cc-2451bd30297f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>vrn_field_hint wizard_vehicle_enquiry_capture_vrn_vrn_error</value>
      <webElementGuid>3d390385-5c5b-4344-bb9d-01373945bd98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>e4b9cd02-8856-495f-87c3-1e5a2d526a7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0cb3690d-970a-40c4-9548-b216ef8dc16b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>wizard_vehicle_enquiry_capture_vrn[vrn]</value>
      <webElementGuid>eb744686-70e0-4fa5-82ec-e487b14cbd2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>wizard_vehicle_enquiry_capture_vrn_vrn</value>
      <webElementGuid>aae99806-c724-4f36-b1ce-c5f4344c4fb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wizard_vehicle_enquiry_capture_vrn_vrn&quot;)</value>
      <webElementGuid>23552118-abdb-47fd-896d-bcfdcfbf7554</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='wizard_vehicle_enquiry_capture_vrn_vrn']</value>
      <webElementGuid>58c8fd7f-8296-4eea-beeb-ffb8db98eb69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-content']/div[2]/div/form/fieldset/div/input</value>
      <webElementGuid>09f3ea64-f282-4822-8d84-f81d3290b862</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div/input</value>
      <webElementGuid>74c1fad4-c4b3-4e22-ae7c-aa348549526d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'wizard_vehicle_enquiry_capture_vrn[vrn]' and @id = 'wizard_vehicle_enquiry_capture_vrn_vrn']</value>
      <webElementGuid>6aea4631-9457-424b-9352-227db411f429</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
