<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Return to GOV.UK</name>
   <tag></tag>
   <elementGuidId>66c2f9e7-f804-4ac5-b40c-c85f6be9819b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.govuk-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick=&quot;trackLinkClick('Return to GOV.UK')&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Return to GOV.UK&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a71a7386-b18b-43d4-8b49-bf9a7e0ecef8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-button</value>
      <webElementGuid>44b9d055-9b56-49a8-9f3b-cc8ee49ca95a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.gov.uk/done/check-vehicle-tax?</value>
      <webElementGuid>75a2721e-b427-4916-b43a-06648d2998cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>trackLinkClick('Return to GOV.UK')</value>
      <webElementGuid>e8b1fb5b-a85e-478e-bff9-0012a0777c0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Return to GOV.UK</value>
      <webElementGuid>958cb21d-2f7a-4f40-b940-a16d79fe6e47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/div[@class=&quot;govuk-grid-row&quot;]/div[@class=&quot;govuk-grid-column-two-thirds&quot;]/p[4]/a[@class=&quot;govuk-button&quot;]</value>
      <webElementGuid>ed346ab1-0105-4b3f-856c-bd4020c6a6ee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick=&quot;trackLinkClick('Return to GOV.UK')&quot;]</value>
      <webElementGuid>c0311056-8c1d-464b-95c0-21b20a684d2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-content']/div[2]/div/p[4]/a</value>
      <webElementGuid>dfa1619b-9b8c-4fef-b028-c5a5f1dc2c8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Return to GOV.UK')]</value>
      <webElementGuid>8265a810-d5a3-48fd-b78b-3b53c4c8f93e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search again'])[1]/following::a[1]</value>
      <webElementGuid>c1f31e3d-5553-4139-9083-2ea2da812f43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='email service'])[1]/following::a[2]</value>
      <webElementGuid>24333903-15a4-4d03-9b66-f68fc324b101</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Support links'])[1]/preceding::a[1]</value>
      <webElementGuid>539c6b16-8ab6-4c50-96d4-8eb354cf20a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cookies'])[1]/preceding::a[1]</value>
      <webElementGuid>f0b0e874-c309-41be-9467-d67a8672c4d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Return to GOV.UK']/parent::*</value>
      <webElementGuid>b7848670-496c-4cd7-a3a0-4fe442baa64c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.gov.uk/done/check-vehicle-tax?')]</value>
      <webElementGuid>99d1a83b-42c2-41e5-a38d-96f130e91d8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[4]/a</value>
      <webElementGuid>de91fa95-102d-49d9-ba42-eda077ab27ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.gov.uk/done/check-vehicle-tax?' and (text() = 'Return to GOV.UK' or . = 'Return to GOV.UK')]</value>
      <webElementGuid>5e601834-ef0a-473c-a8ce-59de00389cc5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
