<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_For example, CU57ABC_wizard_vehicle_e_5f97e0</name>
   <tag></tag>
   <elementGuidId>e2583ae8-79ea-4ff5-8fc8-72c4330aea9d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#wizard_vehicle_enquiry_capture_vrn_vrn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='wizard_vehicle_enquiry_capture_vrn_vrn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Registration number (number plate)&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>811fc4c8-436c-44fe-ab35-26dde60c40e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-input govuk-input--width-10</value>
      <webElementGuid>ee5863de-2ea7-434d-b8e1-096576544d32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>8c3adc03-aba9-46a0-b13d-71b5ad9593e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>de59a100-f1bf-4d25-80c3-f40f2d4945b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>vrn_field_hint wizard_vehicle_enquiry_capture_vrn_vrn_error</value>
      <webElementGuid>89bdc475-646b-4bb0-a593-cf3077f6b3c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>917df855-556d-4d56-b0df-c53e2ab7a13a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3981d4c8-7249-4e48-8e39-152ccb9e3ab4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>wizard_vehicle_enquiry_capture_vrn[vrn]</value>
      <webElementGuid>c8782a5a-1d96-4f57-96a0-a14ec97706cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>wizard_vehicle_enquiry_capture_vrn_vrn</value>
      <webElementGuid>324d6129-5af5-4c07-bf9b-d09c056c57c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wizard_vehicle_enquiry_capture_vrn_vrn&quot;)</value>
      <webElementGuid>810c581e-2489-4ab0-8a58-85eef8b6c5aa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='wizard_vehicle_enquiry_capture_vrn_vrn']</value>
      <webElementGuid>f677d04b-4de5-452a-9ee4-d4c6adfc1b76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-content']/div[2]/div/form/fieldset/div/input</value>
      <webElementGuid>0990430b-5e44-48e0-b7a6-64442d7e8ad9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div/input</value>
      <webElementGuid>8d49a6cc-6901-4761-bd45-90c26daf280b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'wizard_vehicle_enquiry_capture_vrn[vrn]' and @id = 'wizard_vehicle_enquiry_capture_vrn_vrn']</value>
      <webElementGuid>a1040df2-071d-4d44-b541-9b6c5b9e5e4c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
