<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Send feedback</name>
   <tag></tag>
   <elementGuidId>be2882b0-feed-4a31-9479-f2cd73f3c369</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.gem-c-button.govuk-button.gem-c-button--bottom-margin</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='submit'])[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Send feedback&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>608732d4-1a14-4f26-a27a-550efb514ece</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gem-c-button govuk-button gem-c-button--bottom-margin</value>
      <webElementGuid>ae688f1a-42d2-46d0-8954-ddccacf7bbdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>05de4afe-cb74-4340-b1d0-80ad92962c07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Send feedback</value>
      <webElementGuid>615cbb48-475c-4392-b5a0-e95d4082c333</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;govuk-grid-row&quot;]/div[@class=&quot;govuk-grid-column-two-thirds&quot;]/form[@class=&quot;service-feedback&quot;]/button[@class=&quot;gem-c-button govuk-button gem-c-button--bottom-margin&quot;]</value>
      <webElementGuid>bde11a73-e87f-45af-8569-13997daaed95</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='submit'])[4]</value>
      <webElementGuid>6ef3a857-189a-4d5e-ae47-8bf23066ee18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='content']/div/div[2]/form/button</value>
      <webElementGuid>e27efa51-8057-41d5-b03e-2bc34b315927</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='You can enter up to 1250 characters'])[1]/following::button[1]</value>
      <webElementGuid>9614173c-b86c-4d62-a921-dc6a85fde846</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='How could we improve this service?'])[1]/following::button[1]</value>
      <webElementGuid>6c24c565-c94f-4ceb-9706-f3cbf23a9e88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Services and information'])[2]/preceding::button[1]</value>
      <webElementGuid>944fa3a1-0931-4344-b2ab-c84076c47983</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Benefits'])[2]/preceding::button[1]</value>
      <webElementGuid>ae8dec1c-fd46-4399-b024-383d611dfb9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Send feedback']/parent::*</value>
      <webElementGuid>f9091d30-7374-4244-b1f5-82c7c6356fc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/button</value>
      <webElementGuid>286a18b9-f97b-4e9d-8fb9-0587e92ff344</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Send feedback' or . = 'Send feedback')]</value>
      <webElementGuid>47035f0e-ae28-402c-a95c-f37094f8dfc8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
