<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Very satisfied_service_feedbackservic_aa5eb8</name>
   <tag></tag>
   <elementGuidId>b51b2b07-1425-4eb5-8d86-9edcd353a833</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#service-satisfaction-rating-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='service-satisfaction-rating-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Satisfied&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>df5a3ae8-8647-4fa7-9092-c07211024f68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>33bfaa96-4170-4b12-a317-9a8452df287d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>service_feedback[service_satisfaction_rating]</value>
      <webElementGuid>49021d14-a2cb-4aee-806d-3691a001bafa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>service-satisfaction-rating-1</value>
      <webElementGuid>26816115-9d35-4981-bad8-ef2715edadca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>b0610b0a-045b-42f5-982c-d9f0b0d8a3cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-radios__input</value>
      <webElementGuid>11cc4646-ff31-48e4-8224-1650c52a3cba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;service-satisfaction-rating-1&quot;)</value>
      <webElementGuid>3fabb638-27d7-41c2-b4c9-677f970de0e6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='service-satisfaction-rating-1']</value>
      <webElementGuid>52a981e4-77b7-4d54-9fab-c1434715a24e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='content']/div/div[2]/form/div[2]/fieldset/div/div[2]/input</value>
      <webElementGuid>271cf9ce-ce63-4e43-83f4-df10aaa7ddcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>a74d61b8-6d7c-4b3a-8a99-aaf35648a25b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'service_feedback[service_satisfaction_rating]' and @id = 'service-satisfaction-rating-1']</value>
      <webElementGuid>27b7e007-4455-4673-b9cf-d7bd3fb593c6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
